import type { Metadata } from "next";
import { Geist, Geist_Mono, Meow_Script, Spline_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const splineSans = Spline_Sans({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-sans",
});

const noodle = localFont({
  src: "./fonts/BigNoodleTitling-Regular.woff2",
  weight: "400",
  style: "normal",
  display: "swap",
  fallback: ["Arial Narrow", "Arial", "sans-serif"],
  variable: "--font-noodle",
});

const calloveya = localFont({
  src: "./fonts/Calloveya-Regular.woff",
  weight: "400",
  style: "normal",
  display: "swap",
  fallback: ["Brush Script MT", "Segoe Script", "cursive"],
  variable: "--font-signature",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const meowScript = Meow_Script({
  variable: "--font-script",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, noodle.variable, meowScript.variable, splineSans.variable, calloveya.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
